import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import React from "react";
import MenuBar from "@/components/shared/MenuBar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Unimed - Saude Suplementar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased flex gap-6`}
      >
      <MenuBar />
        {children}
      </body>
    </html>
  );
}
